<?php

namespace AppBundle\Repository;

/**
 * qvBuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvBuildingRepository extends \Doctrine\ORM\EntityRepository
{
}
