<?php

namespace AppBundle\Repository;

/**
 * qvBusinessCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvBusinessCenterRepository extends \Doctrine\ORM\EntityRepository
{
}
