<?php

namespace AppBundle\Repository;

/**
 * qvCheckpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvCheckpointRepository extends \Doctrine\ORM\EntityRepository
{
}
