<?php

namespace AppBundle\Repository;

/**
 * qvCheckpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvCheckpointRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByBuildingId($buildingId)
	{
		return $this->getEntityManager()
		->createQuery("SELECT c from AppBundle:qvCheckpoint c LEFT JOIN c.building b where b.id = :bId")
		->setParameter("bId", $buildingId)->getArrayResult();
	}
}
