<?php

namespace AppBundle\Repository;

/**
 * qvContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvContractRepository extends \Doctrine\ORM\EntityRepository
{
}
