<?php

namespace AppBundle\Repository;

/**
 * qvContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvContractRepository extends \Doctrine\ORM\EntityRepository
{
	public function findContractByLeaser($qvLeaser)
	{
        return $this->getEntityManager()
        ->createQuery(
          'SELECT contract.id, contract.name, contract.leaser, contract.startdate, contract.enddate,
          contract.sectors from AppBundle:qvContract contract JOIN contract.leaser leaser  
         	 WHERE contract.leaser = :name'
            )->setParameter('name', $qvLeaser)->getResult();
    }
    public function findLeaserByContract($qvContract)
	{
        return $this->getEntityManager()
        ->createQuery(
          'SELECT contract from AppBundle:qvContract contract JOIN contract.leaser leaser  
         	 WHERE contract.id = :id'
            )->setParameter('id', $qvContract)->getResult();
    }

     public function findOneByLeaser($qvLeaser)
  {
        return $this->getEntityManager()
        ->createQuery(
          'SELECT contract from AppBundle:qvContract contract JOIN contract.leaser leaser  
           WHERE leaser.id = :id'
            )->setParameter('id', $qvLeaser)->getResult();
    }

    public function findOneByContract($id)
  {
        return $this->getEntityManager()
        ->createQuery(
          'SELECT contract from AppBundle:qvContract contract 
           WHERE contract.id = :id'
            )->setParameter('id', $id)->getSingleResult();
    }
}
