<?php

namespace AppBundle\Repository;
use Doctrine\DBAL\Query\Expression\CompositeExpression;
use Doctrine\DBAL\Connection;

/**
 * qvEntranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvEntranceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCurrentEntrance(){
		return $this->getEntityManager()
		->createQuery('SELECT entrance from AppBundle:qvEntrance entrance where entrance.entrancedate > CURRENT_DATE()')->getResult();
	}

	public function findEntrancesByVisitor($qvVisitor){
		return $this->getEntityManager()
		->createQuery('SELECT entrance from AppBundle:qvEntrance entrance left join entrance.visitor v where v.id =:id')->setParameter("id", $qvVisitor)->getResult();
	}
}
