<?php

namespace AppBundle\Repository;

/**
 * qvEntranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvEntranceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCurrentEntrance(){
		return $this->getEntityManager()
		->createQuery('SELECT entrance from AppBundle:qvEntrance entrance where entrance.entrancedate > CURRENT_DATE()')->getResult();
	}

}
