<?php

namespace AppBundle\Repository;

/**
 * qvFloorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvFloorRepository extends \Doctrine\ORM\EntityRepository
{
}
