<?php

namespace AppBundle\Repository;

/**
 * qvGenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvGenderRepository extends \Doctrine\ORM\EntityRepository
{
}
