<?php

namespace AppBundle\Repository;

/**
 * qvHotEntranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvHotEntranceRepository extends \Doctrine\ORM\EntityRepository
{
}
