<?php

namespace AppBundle\Repository;

/**
 * qvHotEntranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvHotEntranceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll(){
		return $this->findBy(array(), array('entrancedate' => 'desc'));
	}
	public function findCurrentHotEntrance(){
		return $this->getEntityManager()
		->createQuery('SELECT hotentrance from AppBundle:qvHotEntrance hotentrance where hotentrance.entrancedate > CURRENT_DATE()')->getResult();
	}
}
