<?php

namespace AppBundle\Repository;

/**
 * qvLeaserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvLeaserRepository extends \Doctrine\ORM\EntityRepository
{
}
