<?php

namespace AppBundle\Repository;

/**
 * qvOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
