<?php

namespace AppBundle\Repository;

/**
 * qvOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvOrderRepository extends \Doctrine\ORM\EntityRepository
{
	public function findActiveOrders()
	{
		return $this->getEntityManager()
        ->createQuery(
          'SELECT c from AppBundle:qvOrder c 
          WHERE c.edate > CURRENT_DATE()'//' AND c.closetime > CURRENT_TIME()'
            )->getResult();
	}
}
