<?php

namespace AppBundle\Repository;

/**
 * qvOrderTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvOrderTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
