<?php

namespace AppBundle\Repository;

/**
 * qvRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
