<?php

namespace AppBundle\Repository;

/**
 * qvRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvRoleRepository extends \Doctrine\ORM\EntityRepository
{
		public function findByCodeLeaser()
	{
        return $this->getEntityManager()
        ->createQuery(
          'SELECT role.id, role.code, role.name from AppBundle:qvRole role 
          WHERE role.code = :code'
            )->setParameter('code', 'ROLE_LEASER')->getResult();
    }

    public function findByCodeCheckpoint()
	{
        return $this->getEntityManager()
        ->createQuery(
          'SELECT role.id, role.code, role.name from AppBundle:qvRole role 
          WHERE role.code = :code'
            )->setParameter('code', 'ROLE_CHECKPOINT')->getResult();
    }
}
