<?php

namespace AppBundle\Repository;

/**
 * qvSectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvSectorRepository extends \Doctrine\ORM\EntityRepository
{
	
public function findFloorById($id)
{
    return $this->getEntityManager()
        ->createQuery(
        	'SELECT sector.floor FROM AppBundle:qvSector sector
            WHERE sector.id = :id'
        )->setParameter('id', $id)->getResult(); 
}

public function findBuildById($id)
{
    return  $this->getEntityManager()
        ->createQuery('
            SELECT sector.id, floor.id, bld.id FROM AppBundle:qvSector sector LEFT JOIN 
            sector.floor floor LEFT JOIN floor.building bld
            WHERE sector.id = :id'
        )->setParameter('id', $id)->getResult();
}
}
