<?php

namespace AppBundle\Repository;

/**
 * qvSectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvSectorRepository extends \Doctrine\ORM\EntityRepository
{
	
public function findFloorById($id)
{
    $query = $this->getEntityManager()
        ->createQuery('
            SELECT sector.floor FROM AppBundle:qvSector sector
            WHERE sector.id = :id'
        )->setParameter('id', $id); 
}
}
