<?php

namespace AppBundle\Repository;

/**
 * qvSectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvSectorRepository extends \Doctrine\ORM\EntityRepository
{
	
public function findFloorById($id)
{
    return $this->getEntityManager()
        ->createQuery(
        	'SELECT sector.floor FROM AppBundle:qvSector sector
            WHERE sector.id = :id'
        )->setParameter('id', $id)->getResult(); 
}

public function findBuildById($id)
{
    return  $this->getEntityManager()
        ->createQuery('
            SELECT sector, floor, bld FROM AppBundle:qvSector sector LEFT JOIN 
            sector.floor floor LEFT JOIN floor.building bld
            WHERE sector.id = :id'
        )->setParameter('id', $id)->getResult();
}

 public function findSectorByContract($id){
      $conn = $this->getEntityManager()->getConnection();
    $statement = $conn->prepare('Select qvsector.id, qvsector.name from qvsector 
              left join rf_contract_sector on rf_contract_sector.sectorid = qvsector.id
             
              left join qvcontract on qvcontract.id = rf_contract_sector.contractid
             
                    where qvcontract.id = ?
                    group by qvsector.id');
    $statement->bindValue(1, $id);
    $statement->execute();
    $result = $statement->fetchAll();
    return $result;
    }

     public function findByFloorId($floorId)
    {
        return $this->getEntityManager()
        ->createQuery("SELECT c from AppBundle:qvSector c LEFT JOIN c.floor f where f.id = :fId")
        ->setParameter("fId", $floorId)->getArrayResult();
    }
}
