<?php

namespace AppBundle\Repository;

/**
 * qvUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvUserRepository extends \Doctrine\ORM\EntityRepository
{
}
