<?php

namespace AppBundle\Repository;

/**
 * qvUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvUserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findUser($qvLeaser) {
		return $this->getEntityManager()
		            ->createQuery(
			'SELECT u FROM AppBundle:qvUser u
    			WHERE u.leaser = :id'
		)->setParameter('id', $qvLeaser)->getSingleResult();
	}
}
