<?php

namespace AppBundle\Repository;

/**
 * qvUserPassportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvUserPassportRepository extends \Doctrine\ORM\EntityRepository
{
	public function findUserpassportByUserRole()
	{
	 return $this->getEntityManager()
	 ->createQuery(
                'SELECT passport, urole FROM AppBundle:qvUserPassport passport JOIN passport.user user JOIN user.role urole WHERE urole.code = :name'
                    )->setParameter('name', 'ROLE_CHECKPOINT')->getResult();
	}
}
