<?php

namespace AppBundle\Repository;

/**
 * qvUserPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvUserPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
