<?php

namespace AppBundle\Repository;

/**
 * qvUserPassportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvUserPassportRepository extends \Doctrine\ORM\EntityRepository
{
}
