<?php

namespace AppBundle\Repository;

/**
 * qvVisitorDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvVisitorDocRepository extends \Doctrine\ORM\EntityRepository
{
}
