<?php

namespace AppBundle\Repository;

/**
 * qvVisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qvVisitorRepository extends \Doctrine\ORM\EntityRepository
{
}
