app:
    resource: "@AppBundle/Controller/"
    type:     annotation
leaser_registration:
    path:     /leasers/create
    defaults: { _controller: AppBundle:AdminBCController:leasers/create }


    
