# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
# http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_db:
            entity:
                class: AppBundle:qvUser
                property: login
        in_memory:
            memory:
             users:
              admin@qvisitor.com:
               password: 'admin'
               roles: 'ROLE_ADMIN'
              checkpoint@qvisitor.com:
               password: 'checkpoint'
               roles: 'ROLE_CHECKPOINT'
              leaser@qvisitor.com:
               password: 'leaser'
               roles: 'ROLE_LEASER'
              sa@qvisitor.com:
               password: 'sa'
               roles: 'ROLE_SA'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Symfony\Component\Security\Core\User\UserInterface: bcrypt
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:    
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                provider: in_db
            logout:
                path:   /logout